export interface TableDef {
  name: string
  rows: number | null
  fields: string[]
}

export interface Layer {
  id: number
  name: string
  description: string
  detail: string
  whyItMatters: string
  tables: TableDef[]
  color: string
  dot: string
  accent: string
  border: string
}

export const LAYERS: Layer[] = [
  {
    id: 1,
    name: 'Source Layer',
    description: 'Raw files — ECB / BIS / BISTA',
    detail: 'Four external data sets ingested as-is: ECB Supervisory Banking Statistics (Excel), BIS statistics (CSV), BISTA bank-level data (CSV), ECB Eurosystem balance sheet (XML/CSV). Generated by regulators and loaded without modification.',
    whyItMatters: 'This is the ground truth. If a regulator ever questions a figure, we can trace it back to the exact raw file and line number. Nothing is altered at this stage — ever.',
    tables: [
      { name: 'data/raw/ecb_sup/ (Excel)', rows: 855, fields: ['REF_AREA', 'INSTRUMENT', 'DATA_TYPE', 'OBS_VALUE', 'TIME_PERIOD'] },
      { name: 'data/raw/bista/ (CSV)', rows: 1029756, fields: ['bank_id', 'report_date', 'item_code', 'value', 'currency'] },
      { name: 'data/raw/eba/ (CSV/XML)', rows: 4101, fields: ['reporting_entity', 'template', 'row', 'col', 'value'] },
      { name: 'data/raw/ecb_sup/ (Eurosystem)', rows: 1134, fields: ['date', 'asset_class', 'counterparty', 'amount_eur'] },
    ],
    color: 'bg-slate-50 text-slate-700',
    dot: 'bg-slate-400',
    accent: 'text-slate-600',
    border: 'border-slate-300',
  },
  {
    id: 2,
    name: 'Staging Layer',
    description: 'PostgreSQL — schema: staging',
    detail: 'Raw data loaded verbatim into typed PostgreSQL tables. No transformations — only type coercion (string → numeric). Each row carries a load_timestamp and source_file path for full provenance.',
    whyItMatters: 'Regulators such as the ECB or national competent authorities can request an audit at any time. The staging layer is our immutable ledger — retained for 7 years. If the warehouse ever needs to be rebuilt, staging is the source of truth.',
    tables: [
      { name: 'staging.ecb_supervisory_raw', rows: 855, fields: ['id', 'ref_area', 'instrument', 'obs_value', 'time_period', 'load_ts', 'source_file'] },
      { name: 'staging.bista_raw', rows: 1029756, fields: ['id', 'bank_id', 'report_date', 'item_code', 'value', 'load_ts'] },
      { name: 'staging.eba_raw', rows: 4101, fields: ['id', 'entity', 'template', 'row_key', 'col_key', 'value', 'load_ts'] },
      { name: 'staging.ecb_eurosystem_raw', rows: 1134, fields: ['id', 'date', 'asset_class', 'amount_eur', 'load_ts'] },
    ],
    color: 'bg-blue-50 text-blue-700',
    dot: 'bg-blue-400',
    accent: 'text-blue-600',
    border: 'border-blue-200',
  },
  {
    id: 3,
    name: 'Warehouse Layer',
    description: 'PostgreSQL — schema: warehouse',
    detail: 'Basel III mapping rules applied in Python (services/transform.py). HQLA assets classified by liquidity tier and haircut applied. Net outflows computed using regulatory run-off rates. LCR = HQLA ÷ Net 30-day Outflow. NSFR = ASF ÷ RSF.',
    whyItMatters: 'This is where raw ECB index numbers become regulatory ratios. Every formula here is traceable to CRR Article 412 (LCR) and Article 428 (NSFR). Auditors can review the SQL views to verify the mapping is correct.',
    tables: [
      { name: 'warehouse.bank_lcr', rows: 38, fields: ['bank_id', 'reference_date', 'hqla_amount', 'net_outflow', 'lcr_ratio', 'computed_at'] },
      { name: 'warehouse.bank_nsfr', rows: 19, fields: ['bank_id', 'reference_date', 'asf_amount', 'rsf_amount', 'nsfr_ratio', 'computed_at'] },
      { name: 'warehouse.supervisory_series', rows: 855, fields: ['series_key', 'ref_area', 'instrument', 'obs_value', 'time_period'] },
    ],
    color: 'bg-indigo-50 text-indigo-700',
    dot: 'bg-indigo-400',
    accent: 'text-indigo-600',
    border: 'border-indigo-200',
  },
  {
    id: 4,
    name: 'Validation Layer',
    description: 'PostgreSQL — schema: validation',
    detail: 'Business rules execute after each warehouse load. Examples: LCR must be positive, HQLA must exceed outflows when LCR > 100%, NSFR ASF must be positive. Failures are written to validation.rule_results with a severity level and blocked from reaching the API.',
    whyItMatters: 'This layer stops bad data from reaching risk managers and regulators. A silent error in a Basel III report can result in a capital misstatement. Every failure is timestamped and logged — not silently discarded.',
    tables: [
      { name: 'validation.rule_results', rows: null, fields: ['id', 'run_id', 'rule_name', 'severity', 'row_ref', 'message', 'checked_at'] },
      { name: 'validation.pipeline_runs', rows: null, fields: ['id', 'started_at', 'finished_at', 'status', 'trigger'] },
    ],
    color: 'bg-amber-50 text-amber-700',
    dot: 'bg-amber-400',
    accent: 'text-amber-600',
    border: 'border-amber-200',
  },
  {
    id: 5,
    name: 'Reporting Layer',
    description: 'FastAPI REST API + React Dashboard',
    detail: 'FastAPI reads from warehouse views and serves typed JSON to the React dashboard. Data is available for LCR, NSFR, data quality, and lineage. Audience: Risk Managers, CFO, Regulators.',
    whyItMatters: 'The dashboard is the final mile — where data becomes decisions. LCR and NSFR breaches trigger alerts that can result in capital raises, asset disposals, or regulatory notification within 24 hours under CRD IV Article 414.',
    tables: [
      { name: 'Summary endpoint', rows: null, fields: ['lcr_ratio', 'nsfr_ratio', 'data_quality_score', 'lcr_trend[]', 'active_alerts[]'] },
      { name: 'LCR metrics endpoint', rows: null, fields: ['banks[].bank_id', 'banks[].lcr_ratio', 'banks[].hqla_amount', 'avg_lcr', 'min_lcr'] },
      { name: 'NSFR metrics endpoint', rows: null, fields: ['banks[].nsfr_ratio', 'banks[].asf_amount', 'banks[].rsf_amount', 'avg_nsfr'] },
    ],
    color: 'bg-emerald-50 text-emerald-700',
    dot: 'bg-emerald-400',
    accent: 'text-emerald-600',
    border: 'border-emerald-200',
  },
]

export type Metric = 'LCR ratio' | 'NSFR ratio'

export const QUARTERS = [
  '2025 Q4', '2025 Q3', '2025 Q2', '2025 Q1',
  '2024 Q4', '2024 Q3', '2024 Q2', '2024 Q1',
]

export interface TraceStep {
  layer: string
  color: string
  icon: string
  detail: string
}

export function buildTrace(metric: Metric, quarter: string): TraceStep[] {
  const isLcr = metric === 'LCR ratio'
  const [year, q] = quarter.split(' ')
  const month = ({ Q1: '03', Q2: '06', Q3: '09', Q4: '12' } as Record<string, string>)[q] ?? '12'
  const refDate = `${year}-${month}-31`
  const qNoSpace = quarter.replace(' ', '')

  return [
    {
      layer: 'Source File',
      color: 'border-slate-300 bg-slate-50',
      icon: 'SRC',
      detail: isLcr
        ? `data/raw/ecb_sup/ECB_SUP_LCR_*.xlsx — sheet "LCR", row where TIME_PERIOD="${qNoSpace}" and REF_AREA="U2". OBS_VALUE column contains the raw index figure.`
        : `data/raw/ecb_sup/ECB_SUP_NSFR_*.xlsx — sheet "NSFR", row where TIME_PERIOD="${qNoSpace}" and REF_AREA="U2". OBS_VALUE column contains the raw index figure.`,
    },
    {
      layer: 'Staging Row',
      color: 'border-blue-200 bg-blue-50',
      icon: 'STG',
      detail: isLcr
        ? `staging.ecb_supervisory_raw WHERE instrument='LCR_RATIO' AND ref_area='U2' AND time_period='${qNoSpace}' — load_ts records exactly when the file was ingested. source_file path preserved for audit.`
        : `staging.ecb_supervisory_raw WHERE instrument='NSFR_RATIO' AND ref_area='U2' AND time_period='${qNoSpace}' — identically structured to LCR rows, same audit fields.`,
    },
    {
      layer: 'Warehouse Record',
      color: 'border-indigo-200 bg-indigo-50',
      icon: 'WH',
      detail: isLcr
        ? `warehouse.bank_lcr WHERE bank_id='ECB_EU_AGGREGATE' AND reference_date='${refDate}'. Fields: hqla_amount (HQLA index), net_outflow (30-day net outflow index), lcr_ratio = hqla_amount / net_outflow × 100. Computed by services/transform.py.`
        : `warehouse.bank_nsfr WHERE bank_id='ECB_EU_AGGREGATE' AND reference_date='${refDate}'. Fields: asf_amount (Available Stable Funding), rsf_amount (Required Stable Funding), nsfr_ratio = asf_amount / rsf_amount × 100.`,
    },
    {
      layer: 'API Response',
      color: 'border-emerald-200 bg-emerald-50',
      icon: 'API',
      detail: isLcr
        ? `The LCR metrics endpoint returns response.banks[0].lcr_ratio for this record. The same figure is also available in the Summary endpoint as lcr_ratio (latest quarter) and lcr_trend[].lcr_ratio (all quarters). The value you see on the dashboard is this exact field.`
        : `The NSFR metrics endpoint returns response.banks[0].nsfr_ratio for this record. The same figure is surfaced in the Summary endpoint as nsfr_ratio (latest quarter). The value you see on the NSFR Detail page and Executive Summary card is this exact field.`,
    },
    {
      layer: 'Dashboard Figure',
      color: 'border-emerald-300 bg-emerald-100',
      icon: 'UI',
      detail: isLcr
        ? `Displayed on the Executive Summary page (LCR card) and LCR Detail page (trend chart + stat cards). If you opened the stress test slider, the displayed value is lcr_ratio × (1 − shock/100) — but the underlying warehouse record is unchanged.`
        : `Displayed on the Executive Summary page (NSFR card) and NSFR Detail page (trend chart + stat cards). The stress test slider on Executive Summary applies the same shock coefficient to this value.`,
    },
  ]
}

export function getHighlightTable(layerId: number, metric: Metric | null): string | undefined {
  if (!metric) return undefined
  const isLcr = metric === 'LCR ratio'
  switch (layerId) {
    case 1: return 'data/raw/ecb_sup/ (Excel)'
    case 2: return 'staging.ecb_supervisory_raw'
    case 3: return isLcr ? 'warehouse.bank_lcr' : 'warehouse.bank_nsfr'
    case 4: return 'validation.rule_results'
    case 5: return isLcr ? 'LCR metrics endpoint' : 'NSFR metrics endpoint'
  }
}
