import { useState } from 'react'

// ── layer definitions ────────────────────────────────────────────────────────

interface Layer {
  id: number
  name: string
  description: string
  detail: string
  whyItMatters: string
  tables: { name: string; rows: number | null; fields: string[] }[]
  color: string
  dot: string
  accent: string
  border: string
}

const LAYERS: Layer[] = [
  {
    id: 1,
    name: 'Source Layer',
    description: 'Raw files — ECB / BIS / BISTA',
    detail: 'Four external data sets ingested as-is: ECB Supervisory Banking Statistics (Excel), BIS statistics (CSV), BISTA bank-level data (CSV), ECB Eurosystem balance sheet (XML/CSV). Generated by regulators and loaded without modification.',
    whyItMatters: 'This is the ground truth. If a regulator ever questions a figure, we can trace it back to the exact raw file and line number. Nothing is altered at this stage — ever.',
    tables: [
      { name: 'data/raw/ecb_sup/ (Excel)', rows: 855, fields: ['REF_AREA', 'INSTRUMENT', 'DATA_TYPE', 'OBS_VALUE', 'TIME_PERIOD'] },
      { name: 'data/raw/bista/ (CSV)', rows: 1029756, fields: ['bank_id', 'report_date', 'item_code', 'value', 'currency'] },
      { name: 'data/raw/eba/ (CSV/XML)', rows: 4101, fields: ['reporting_entity', 'template', 'row', 'col', 'value'] },
      { name: 'data/raw/ecb_sup/ (Eurosystem)', rows: 1134, fields: ['date', 'asset_class', 'counterparty', 'amount_eur'] },
    ],
    color: 'bg-slate-50 text-slate-700',
    dot: 'bg-slate-400',
    accent: 'text-slate-600',
    border: 'border-slate-300',
  },
  {
    id: 2,
    name: 'Staging Layer',
    description: 'PostgreSQL — schema: staging',
    detail: 'Raw data loaded verbatim into typed PostgreSQL tables. No transformations — only type coercion (string → numeric). Each row carries a load_timestamp and source_file path for full provenance.',
    whyItMatters: 'Regulators such as the ECB or national competent authorities can request an audit at any time. The staging layer is our immutable ledger — retained for 7 years. If the warehouse ever needs to be rebuilt, staging is the source of truth.',
    tables: [
      { name: 'staging.ecb_supervisory_raw', rows: 855, fields: ['id', 'ref_area', 'instrument', 'obs_value', 'time_period', 'load_ts', 'source_file'] },
      { name: 'staging.bista_raw', rows: 1029756, fields: ['id', 'bank_id', 'report_date', 'item_code', 'value', 'load_ts'] },
      { name: 'staging.eba_raw', rows: 4101, fields: ['id', 'entity', 'template', 'row_key', 'col_key', 'value', 'load_ts'] },
      { name: 'staging.ecb_eurosystem_raw', rows: 1134, fields: ['id', 'date', 'asset_class', 'amount_eur', 'load_ts'] },
    ],
    color: 'bg-blue-50 text-blue-700',
    dot: 'bg-blue-400',
    accent: 'text-blue-600',
    border: 'border-blue-200',
  },
  {
    id: 3,
    name: 'Warehouse Layer',
    description: 'PostgreSQL — schema: warehouse',
    detail: 'Basel III mapping rules applied in Python (services/transform.py). HQLA assets classified by liquidity tier and haircut applied. Net outflows computed using regulatory run-off rates. LCR = HQLA ÷ Net 30-day Outflow. NSFR = ASF ÷ RSF.',
    whyItMatters: 'This is where raw ECB index numbers become regulatory ratios. Every formula here is traceable to CRR Article 412 (LCR) and Article 428 (NSFR). Auditors can review the SQL views to verify the mapping is correct.',
    tables: [
      { name: 'warehouse.bank_lcr', rows: 38, fields: ['bank_id', 'reference_date', 'hqla_amount', 'net_outflow', 'lcr_ratio', 'computed_at'] },
      { name: 'warehouse.bank_nsfr', rows: 19, fields: ['bank_id', 'reference_date', 'asf_amount', 'rsf_amount', 'nsfr_ratio', 'computed_at'] },
      { name: 'warehouse.supervisory_series', rows: 855, fields: ['series_key', 'ref_area', 'instrument', 'obs_value', 'time_period'] },
    ],
    color: 'bg-indigo-50 text-indigo-700',
    dot: 'bg-indigo-400',
    accent: 'text-indigo-600',
    border: 'border-indigo-200',
  },
  {
    id: 4,
    name: 'Validation Layer',
    description: 'PostgreSQL — schema: validation',
    detail: 'Business rules execute after each warehouse load. Examples: LCR must be positive, HQLA must exceed outflows when LCR > 100%, NSFR ASF must be positive. Failures are written to validation.rule_results with a severity level and blocked from reaching the API.',
    whyItMatters: 'This layer stops bad data from reaching risk managers and regulators. A silent error in a Basel III report can result in a capital misstatement. Every failure is timestamped and logged — not silently discarded.',
    tables: [
      { name: 'validation.rule_results', rows: null, fields: ['id', 'run_id', 'rule_name', 'severity', 'row_ref', 'message', 'checked_at'] },
      { name: 'validation.pipeline_runs', rows: null, fields: ['id', 'started_at', 'finished_at', 'status', 'trigger'] },
    ],
    color: 'bg-amber-50 text-amber-700',
    dot: 'bg-amber-400',
    accent: 'text-amber-600',
    border: 'border-amber-200',
  },
  {
    id: 5,
    name: 'Reporting Layer',
    description: 'FastAPI REST API + React Dashboard',
    detail: 'FastAPI reads from warehouse views and serves typed JSON endpoints: /api/v1/lcr, /api/v1/nsfr, /api/v1/summary, /api/v1/quality, /api/v1/lineage. This React dashboard consumes those endpoints. Audience: Risk Managers, CFO, Regulators.',
    whyItMatters: 'The dashboard is the final mile — where data becomes decisions. LCR and NSFR breaches trigger alerts that can result in capital raises, asset disposals, or regulatory notification within 24 hours under CRD IV Article 414.',
    tables: [
      { name: 'GET /api/v1/summary', rows: null, fields: ['lcr_ratio', 'nsfr_ratio', 'data_quality_score', 'lcr_trend[]', 'active_alerts[]'] },
      { name: 'GET /api/v1/lcr', rows: null, fields: ['banks[].bank_id', 'banks[].lcr_ratio', 'banks[].hqla_amount', 'avg_lcr', 'min_lcr'] },
      { name: 'GET /api/v1/nsfr', rows: null, fields: ['banks[].nsfr_ratio', 'banks[].asf_amount', 'banks[].rsf_amount', 'avg_nsfr'] },
    ],
    color: 'bg-emerald-50 text-emerald-700',
    dot: 'bg-emerald-400',
    accent: 'text-emerald-600',
    border: 'border-emerald-200',
  },
]

// ── trace definitions ────────────────────────────────────────────────────────

type Metric = 'LCR ratio' | 'NSFR ratio'

const QUARTERS = [
  '2025 Q4', '2025 Q3', '2025 Q2', '2025 Q1',
  '2024 Q4', '2024 Q3', '2024 Q2', '2024 Q1',
]

interface TraceStep {
  layer: string
  color: string
  icon: string
  detail: string
}

function buildTrace(metric: Metric, quarter: string): TraceStep[] {
  const isLcr = metric === 'LCR ratio'
  const [year, q] = quarter.split(' ')
  const month = { Q1: '03', Q2: '06', Q3: '09', Q4: '12' }[q] ?? '12'
  const refDate = `${year}-${month}-31`

  return [
    {
      layer: 'Source File',
      color: 'border-slate-300 bg-slate-50',
      icon: '📂',
      detail: isLcr
        ? `data/raw/ecb_sup/ECB_SUP_LCR_*.xlsx — sheet "LCR", row where TIME_PERIOD="${quarter.replace(' ', '')}" and REF_AREA="U2". OBS_VALUE column contains the raw index figure.`
        : `data/raw/ecb_sup/ECB_SUP_NSFR_*.xlsx — sheet "NSFR", row where TIME_PERIOD="${quarter.replace(' ', '')}" and REF_AREA="U2". OBS_VALUE column contains the raw index figure.`,
    },
    {
      layer: 'Staging Row',
      color: 'border-blue-200 bg-blue-50',
      icon: '🗄️',
      detail: isLcr
        ? `staging.ecb_supervisory_raw WHERE instrument='LCR_RATIO' AND ref_area='U2' AND time_period='${quarter.replace(' ', '')}' — load_ts records exactly when the file was ingested. source_file path preserved for audit.`
        : `staging.ecb_supervisory_raw WHERE instrument='NSFR_RATIO' AND ref_area='U2' AND time_period='${quarter.replace(' ', '')}' — identically structured to LCR rows, same audit fields.`,
    },
    {
      layer: 'Warehouse Record',
      color: 'border-indigo-200 bg-indigo-50',
      icon: '🏭',
      detail: isLcr
        ? `warehouse.bank_lcr WHERE bank_id='ECB_EU_AGGREGATE' AND reference_date='${refDate}'. Fields: hqla_amount (HQLA index), net_outflow (30-day net outflow index), lcr_ratio = hqla_amount / net_outflow × 100. Computed by services/transform.py.`
        : `warehouse.bank_nsfr WHERE bank_id='ECB_EU_AGGREGATE' AND reference_date='${refDate}'. Fields: asf_amount (Available Stable Funding), rsf_amount (Required Stable Funding), nsfr_ratio = asf_amount / rsf_amount × 100.`,
    },
    {
      layer: 'API Response',
      color: 'border-emerald-200 bg-emerald-50',
      icon: '🔌',
      detail: isLcr
        ? `GET /api/v1/lcr → response.banks[0].lcr_ratio. Also surfaced in GET /api/v1/summary → lcr_ratio (latest quarter) and lcr_trend[].lcr_ratio (all quarters). The value you see on the dashboard is this exact field.`
        : `GET /api/v1/nsfr → response.banks[0].nsfr_ratio. Also surfaced in GET /api/v1/summary → nsfr_ratio (latest quarter). The value you see on the NSFR Detail page and Executive Summary card is this exact field.`,
    },
    {
      layer: 'Dashboard Figure',
      color: 'border-emerald-300 bg-emerald-100',
      icon: '📊',
      detail: isLcr
        ? `Displayed on the Executive Summary page (LCR card) and LCR Detail page (trend chart + stat cards). If you opened the stress test slider, the displayed value is lcr_ratio × (1 − shock/100) — but the underlying warehouse record is unchanged.`
        : `Displayed on the Executive Summary page (NSFR card) and NSFR Detail page (trend chart + stat cards). The stress test slider on Executive Summary applies the same shock coefficient to this value.`,
    },
  ]
}

// ── data flow diagram (SVG) ──────────────────────────────────────────────────

function DataFlowDiagram() {
  // Node dimensions
  const nodeW = 180, nodeH = 56, rx = 10
  // Positions (viewBox 560 × 300)
  const bista   = { x: 40,  y: 30 }
  const ecb     = { x: 340, y: 30 }
  const mapping = { x: 190, y: 140 }
  const dash    = { x: 190, y: 240 }

  // Arrow helper: mid-center of a node
  const cx = (n: { x: number }) => n.x + nodeW / 2
  const cy = (n: { y: number }) => n.y + nodeH / 2
  const bot = (n: { y: number }) => n.y + nodeH
  const top = (n: { y: number }) => n.y

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-6">
      <h2 className="text-base font-semibold text-gray-800 mb-1">Data Flow Overview</h2>
      <p className="text-xs text-gray-400 mb-5">
        How source data travels from granular sub-ledger and top-down reporting into the executive dashboard.
      </p>
      <div className="overflow-x-auto">
        <svg viewBox="0 0 560 316" className="w-full max-w-2xl mx-auto" style={{ minWidth: 340 }}>
          <defs>
            <marker id="arrowhead" markerWidth="8" markerHeight="6" refX="8" refY="3" orient="auto">
              <polygon points="0 0, 8 3, 0 6" fill="#94a3b8" />
            </marker>
            <marker id="arrowhead-indigo" markerWidth="8" markerHeight="6" refX="8" refY="3" orient="auto">
              <polygon points="0 0, 8 3, 0 6" fill="#6366f1" />
            </marker>
          </defs>

          {/* ── BISTA node ── */}
          <rect x={bista.x} y={bista.y} width={nodeW} height={nodeH} rx={rx} fill="#f8fafc" stroke="#94a3b8" strokeWidth={1.5} />
          <text x={cx(bista)} y={bista.y + 22} textAnchor="middle" style={{ font: 'bold 12px sans-serif', fill: '#334155' }}>
            BISTA
          </text>
          <text x={cx(bista)} y={bista.y + 38} textAnchor="middle" style={{ font: '10px sans-serif', fill: '#64748b' }}>
            Bundesbank Master File
          </text>
          <text x={cx(bista)} y={bista.y + 52} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#94a3b8' }}>
            Granular Sub-ledger
          </text>

          {/* ── ECB node ── */}
          <rect x={ecb.x} y={ecb.y} width={nodeW} height={nodeH} rx={rx} fill="#eef2ff" stroke="#6366f1" strokeWidth={1.5} />
          <text x={cx(ecb)} y={ecb.y + 22} textAnchor="middle" style={{ font: 'bold 12px sans-serif', fill: '#3730a3' }}>
            ECB Supervisory Extract
          </text>
          <text x={cx(ecb)} y={ecb.y + 38} textAnchor="middle" style={{ font: '10px sans-serif', fill: '#4f46e5' }}>
            Top-Down Reporting
          </text>
          <text x={cx(ecb)} y={ecb.y + 52} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#818cf8' }}>
            Reconciliation source
          </text>

          {/* ── Validation & Mapping node ── */}
          <rect x={mapping.x} y={mapping.y} width={nodeW} height={nodeH} rx={rx} fill="#fffbeb" stroke="#f59e0b" strokeWidth={1.5} />
          <text x={cx(mapping)} y={mapping.y + 22} textAnchor="middle" style={{ font: 'bold 12px sans-serif', fill: '#92400e' }}>
            Validation & Mapping
          </text>
          <text x={cx(mapping)} y={mapping.y + 38} textAnchor="middle" style={{ font: '10px sans-serif', fill: '#b45309' }}>
            CRR Art. 416 / 422
          </text>
          <text x={cx(mapping)} y={mapping.y + 52} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#d97706' }}>
            Run-off weights applied
          </text>

          {/* ── Dashboard node ── */}
          <rect x={dash.x} y={dash.y} width={nodeW} height={nodeH} rx={rx} fill="#f0fdf4" stroke="#10b981" strokeWidth={2} />
          <text x={cx(dash)} y={dash.y + 22} textAnchor="middle" style={{ font: 'bold 12px sans-serif', fill: '#065f46' }}>
            Executive Dashboard
          </text>
          <text x={cx(dash)} y={dash.y + 38} textAnchor="middle" style={{ font: '10px sans-serif', fill: '#047857' }}>
            LCR / NSFR
          </text>
          <text x={cx(dash)} y={dash.y + 52} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#34d399' }}>
            Risk Managers · CFO · Regulators
          </text>

          {/* ── Arrow: BISTA → Mapping ── */}
          <line
            x1={cx(bista)} y1={bot(bista)}
            x2={cx(mapping)} y2={top(mapping) - 2}
            stroke="#94a3b8" strokeWidth={1.5} markerEnd="url(#arrowhead)"
          />

          {/* ── Arrow: ECB → Mapping (curves in from the right) ── */}
          <path
            d={`M ${cx(ecb)} ${bot(ecb)} C ${cx(ecb)} ${cy(mapping)}, ${cx(mapping) + 60} ${cy(mapping)}, ${cx(mapping) + nodeW / 2 + 2} ${cy(mapping)}`}
            fill="none" stroke="#6366f1" strokeWidth={1.5} markerEnd="url(#arrowhead-indigo)"
          />

          {/* ── Arrow: Mapping → Dashboard ── */}
          <line
            x1={cx(mapping)} y1={bot(mapping)}
            x2={cx(dash)} y2={top(dash) - 2}
            stroke="#10b981" strokeWidth={1.5} markerEnd="url(#arrowhead)"
          />

          {/* ── Labels on arrows ── */}
          <text x={cx(bista) + 28} y={cy(bista) + 68} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#94a3b8' }}>
            1M+ rows
          </text>
          <text x={cx(ecb) + 40} y={cy(ecb) + 52} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#6366f1' }}>
            top-down reconcile
          </text>
          <text x={cx(mapping) + 34} y={cy(mapping) + 64} textAnchor="middle" style={{ font: '9px sans-serif', fill: '#10b981' }}>
            validated ratios
          </text>
        </svg>
      </div>
    </div>
  )
}

// ── animated flow arrow ──────────────────────────────────────────────────────

function FlowArrow() {
  return (
    <div className="flex justify-center items-center h-8 my-0">
      <div className="flex flex-col items-center gap-0.5 animate-bounce">
        <div className="w-0.5 h-3 bg-gray-300 rounded" />
        <svg width="12" height="8" viewBox="0 0 12 8" fill="none">
          <path d="M6 8L0 0h12L6 8z" fill="#d1d5db" />
        </svg>
      </div>
    </div>
  )
}

// ── expandable layer card ────────────────────────────────────────────────────

function LayerCard({ layer, index, total, isOpen, onToggle, highlightTable }: {
  layer: Layer; index: number; total: number
  isOpen: boolean; onToggle: () => void; highlightTable?: string
}) {
  return (
    <>
      <div
        className={`rounded-xl border ${layer.border} ${layer.color} cursor-pointer select-none transition-all hover:shadow-md ${highlightTable ? 'ring-2 ring-indigo-300 shadow-md' : ''}`}
        onClick={onToggle}
      >
        <div className="flex items-center justify-between px-5 py-4">
          <div className="flex items-center gap-3">
            <div className={`w-3 h-3 rounded-full ${layer.dot} shrink-0`} />
            <div>
              <span className="font-bold text-sm">{layer.name}</span>
              <span className="ml-2 text-xs opacity-60 font-normal">{layer.description}</span>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono opacity-50">{index + 1} / {total}</span>
            <svg
              className={`w-4 h-4 opacity-50 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
              fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </div>

        {isOpen && (
          <div className="px-5 pb-5 border-t border-current border-opacity-10 pt-4 space-y-4" onClick={e => e.stopPropagation()}>
            <p className="text-sm opacity-80 leading-relaxed">{layer.detail}</p>

            {/* Why it matters */}
            <div className="rounded-lg bg-white bg-opacity-60 border border-current border-opacity-10 p-3">
              <p className="text-xs font-semibold uppercase tracking-wide opacity-60 mb-1">Why this matters</p>
              <p className="text-sm leading-relaxed">{layer.whyItMatters}</p>
            </div>

            {/* Tables */}
            <div>
              <p className="text-xs font-semibold uppercase tracking-wide opacity-60 mb-2">Tables / endpoints</p>
              <div className="space-y-2">
                {layer.tables.map(t => (
                  <div key={t.name} className={`rounded-lg bg-white bg-opacity-60 border p-3 transition-colors ${t.name === highlightTable ? 'border-indigo-400 ring-2 ring-indigo-200' : 'border-current border-opacity-10'}`}>
                    <div className="flex items-center justify-between mb-1.5">
                      <code className="text-xs font-mono font-semibold">{t.name}</code>
                      {t.rows != null && (
                        <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-white bg-opacity-80">
                          {t.rows.toLocaleString()} rows
                        </span>
                      )}
                    </div>
                    <p className="text-xs opacity-60 font-mono">{t.fields.join(' · ')}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {index < total - 1 && <FlowArrow />}
    </>
  )
}

// ── trace panel ──────────────────────────────────────────────────────────────

function TracePanel({ onTrace }: { onTrace: (metric: Metric, quarter: string) => void }) {
  const [metric, setMetric] = useState<Metric>('LCR ratio')
  const [quarter, setQuarter] = useState(QUARTERS[0])
  const [traced, setTraced] = useState(false)

  const steps = buildTrace(metric, quarter)

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-6 space-y-5">
      <div>
        <h2 className="text-lg font-bold text-gray-900">Trace a Number</h2>
        <p className="text-sm text-gray-500 mt-1">
          Pick any metric and quarter to see the full audit trail from source file to dashboard figure.
        </p>
      </div>

      <div className="flex flex-wrap gap-3">
        <div className="flex flex-col gap-1">
          <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Metric</label>
          <select
            value={metric}
            onChange={e => { setMetric(e.target.value as Metric); setTraced(false) }}
            className="text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-300"
          >
            <option>LCR ratio</option>
            <option>NSFR ratio</option>
          </select>
        </div>
        <div className="flex flex-col gap-1">
          <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Quarter</label>
          <select
            value={quarter}
            onChange={e => { setQuarter(e.target.value); setTraced(false) }}
            className="text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-300"
          >
            {QUARTERS.map(q => <option key={q}>{q}</option>)}
          </select>
        </div>
        <div className="flex flex-col justify-end">
          <button
            onClick={() => { setTraced(true); onTrace(metric, quarter) }}
            className="bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            Trace →
          </button>
        </div>
      </div>

      {traced && (
        <div className="space-y-2 pt-2">
          <p className="text-xs text-gray-400 font-semibold uppercase tracking-wide mb-3">
            Provenance chain — {metric} for {quarter}
          </p>
          {steps.map((step, i) => (
            <div key={step.layer}>
              <div className={`rounded-lg border ${step.color} p-3`}>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-base">{step.icon}</span>
                  <span className="text-xs font-bold text-gray-700 uppercase tracking-wide">{step.layer}</span>
                </div>
                <p className="text-xs text-gray-600 leading-relaxed">{step.detail}</p>
              </div>
              {i < steps.length - 1 && (
                <div className="flex justify-center py-1">
                  <svg width="10" height="14" viewBox="0 0 10 14" fill="none">
                    <line x1="5" y1="0" x2="5" y2="10" stroke="#d1d5db" strokeWidth="1.5" />
                    <path d="M5 14L1 8h8L5 14z" fill="#d1d5db" />
                  </svg>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// ── page ─────────────────────────────────────────────────────────────────────

function getHighlightTable(layerId: number, metric: Metric | null): string | undefined {
  if (!metric) return undefined
  const isLcr = metric === 'LCR ratio'
  switch (layerId) {
    case 1: return 'data/raw/ecb_sup/ (Excel)'
    case 2: return 'staging.ecb_supervisory_raw'
    case 3: return isLcr ? 'warehouse.bank_lcr' : 'warehouse.bank_nsfr'
    case 4: return 'validation.rule_results'
    case 5: return isLcr ? 'GET /api/v1/lcr' : 'GET /api/v1/nsfr'
  }
}

export default function DataLineage() {
  const [openLayers, setOpenLayers] = useState<Set<number>>(new Set())
  const [tracedMetric, setTracedMetric] = useState<Metric | null>(null)

  function handleTrace(metric: Metric, _quarter: string) {
    setTracedMetric(metric)
    setOpenLayers(new Set([1, 2, 3, 4, 5]))
  }

  function toggleLayer(id: number) {
    setOpenLayers(prev => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Data Lineage</h1>
        <p className="text-sm text-gray-500 mt-1">End-to-end pipeline — source to report. Click any layer to expand.</p>
      </div>

      {/* Why this matters banner */}
      <div className="flex gap-3 rounded-xl border border-indigo-200 bg-indigo-50 px-5 py-4">
        <span className="mt-0.5 shrink-0 text-indigo-500 text-lg">ⓘ</span>
        <p className="text-sm text-indigo-800 leading-relaxed">
          <span className="font-semibold">Why this matters: </span>
          In regulated environments, every number on a board report must be traceable to its source.
          This pipeline is designed to satisfy that requirement — click any layer to inspect the data at that stage.
        </p>
      </div>

      {/* Data flow diagram */}
      <DataFlowDiagram />

      {/* Trace a Number — featured */}
      <TracePanel onTrace={handleTrace} />

      {/* Layer cards */}
      <div>
        {LAYERS.map((layer, i) => (
          <LayerCard
            key={layer.id}
            layer={layer}
            index={i}
            total={LAYERS.length}
            isOpen={openLayers.has(layer.id)}
            onToggle={() => toggleLayer(layer.id)}
            highlightTable={getHighlightTable(layer.id, tracedMetric)}
          />
        ))}
      </div>

      <div className="rounded-xl border border-gray-200 bg-gray-50 p-5 text-sm text-gray-600">
        <p className="font-semibold text-gray-800 mb-2">Key design principles</p>
        <ul className="space-y-1 list-disc list-inside">
          <li>Data is <strong>never modified</strong> in the Staging layer — full audit trail preserved</li>
          <li>All Basel III mappings live in <strong>Python transforms</strong> — versioned and reviewable by auditors</li>
          <li>Validation failures are <strong>logged with timestamps</strong> — not silently discarded</li>
          <li>Each layer has a <strong>clear business owner</strong>: Risk (Warehouse), IT (Staging), Compliance (Validation)</li>
        </ul>
      </div>
    </div>
  )
}
